-- This file is for use with Moai SDK
--
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:dfa35dad66c9c68c20bced414e9d9c29:2ee20a1dcf862c9ee2caea99bc410f72:82237b1f3029e898e3ccc8875ae3da45$
--

return {
    texture = 'BulbousPlant.png',
    frames = {
        {
            name = "bulbous_plant",
            spriteColorRect = { x = 32, y = 36, width = 64, height = 64 },
            uvRect = { u0 = 0, v0 = 0, u1 = 0.976562, v1 = 0.476562 },
            spriteSourceSize = { width = 125, height = 122 },
            spriteTrimmed = true,
            textureRotated = false
        },
        {
            name = "bulbous_plant_icon",
            spriteColorRect = { x = 32, y = 36, width = 64, height = 64 },
            uvRect = { u0 = 0, v0 = 0.476562, u1 = 0.976562, v1 = 0.953125 },
            spriteSourceSize = { width = 125, height = 122 },
            spriteTrimmed = true,
            textureRotated = false
        },
    }
}
