-- This file is for use with Moai SDK
--
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:23e6f0431e3e57a49968401b47ad35c0:143fa5dd85724a7ab58e57619c533e3b:90c1b682f4aa562f6bfa6f810e31f37e$
--

return {
    texture = 'happybot.png',
    frames = {
        {
            name = "HappyBot_destroyed",
            spriteColorRect = { x = 0, y = 0, width = 140, height = 144 },
            uvRect = { u0 = 0, v0 = 0, u1 = 0.696517, v1 = 0.307692 },
            spriteSourceSize = { width = 140, height = 144 },
            spriteTrimmed = true,
            textureRotated = false
        },
        {
            name = "HappyBot_damaged",
            spriteColorRect = { x = 0, y = 0, width = 109, height = 161 },
            uvRect = { u0 = 0, v0 = 0.307692, u1 = 0.542289, v1 = 0.651709 },
            spriteSourceSize = { width = 109, height = 161 },
            spriteTrimmed = true,
            textureRotated = false
        },
        {
            name = "HappyBot_Icon",
            spriteColorRect = { x = 0, y = 30, width = 32, height = 53 },
            uvRect = { u0 = 0.542289, v0 = 0.307692, u1 = 1, v1 = 0.653846 },
            spriteSourceSize = { width = 92, height = 162 },
            spriteTrimmed = true,
            textureRotated = false
        },
        {
            name = "HappyBot_wink",
            spriteColorRect = { x = 0, y = 0, width = 92, height = 162 },
            uvRect = { u0 = 0, v0 = 0.653846, u1 = 0.457711, v1 = 1 },
            spriteSourceSize = { width = 92, height = 162 },
            spriteTrimmed = true,
            textureRotated = false
        },
        {
            name = "HappyBot",
            spriteColorRect = { x = 0, y = 0, width = 92, height = 162 },
            uvRect = { u0 = 0.457711, v0 = 0.653846, u1 = 0.915423, v1 = 1 },
            spriteSourceSize = { width = 92, height = 162 },
            spriteTrimmed = true,
            textureRotated = false
        },
		{
			name = "HappyBot_portrait",
			spriteColorRect = { x = 104, y = -54, width = 42, height = 63 },
			uvRect = { u0 = 0.457711, v0 = 0.653846, u1 = 0.915423, v1 = 1 },
			spriteSourceSize = { width = 46, height = 67 },
			spriteTrimmed = true,
			textureRotated = false
		},
    }
}
