-- This file is for use with Moai SDK
--
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:88b7838a4e829bf16745a0d4a39b6ab3:f1e47ae5168af7b470b29badab1b1121:2c6388c492690ac907d4608a41a39c56$
--

return {
    texture = 'strange_plant.png',
    frames = {
        {
            name = "strange_plant",
            spriteColorRect = { x = 32, y = -8, width = 64, height = 208 },
            uvRect = { u0 = 0, v0 = 0, u1 = 0.320312, v1 = 0.8125 },
            spriteSourceSize = { width = 82, height = 208 },
            spriteTrimmed = true,
            textureRotated = false
        },
        {
            name = "strange_plant_icon",
            spriteColorRect = { x = 32, y = -8, width = 64, height = 208 },
            uvRect = { u0 = 0.320312, v0 = 0, u1 = 0.640625, v1 = 0.8125 },
            spriteSourceSize = { width = 82, height = 208 },
            spriteTrimmed = true,
            textureRotated = false
        },
    }
}
